apiVersion: apps/v1
kind: Deployment
metadata: 
        name: my-deployment
spec:
        replicas: 1
        selector:
          matchLabels:
            app: my-app
        template:
            metadata:
              labels:
                app: my-app
            spec: 
              containers:
              - image: storaxdev/kubedoom:0.5.0
                name: kbd
                ports: 
                - containerPort: 5900
              serviceAccountName: kubedoom
              hostNetwork: true
