apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
      - questbusters.ru
      secretName: questbusters
  rules:
    - host: questbusters.ru
      http:
        paths:
        - backend:
            serviceName: redmine-service
            servicePort: 3000
          path: /
