apiVersion: v1
kind: Service
metadata:
  name: redmine-service
spec:
  selector:
    app: redmine
  ports:
    - name: redmine-port
      protocol: TCP
      port: 3000
      targetPort: 3000
  #type: LoadBalancer/Nodeport
