apiVersion: v1
kind: Secret
metadata:
  name: qb2
  namespace: default
data:
  tls.crt: MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
  MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
  DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
  TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
  cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
  AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
  ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
  wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
  LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
  4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
  bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
  sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
  Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
  FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
  SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
  PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
  TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
  SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
  c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
  +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
  ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
  b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
  U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
  MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
  5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
  9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
  WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
  he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
  Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
  tls.key: MIIEogIBAAKCAQEAmxAXgSlzLx1F6rH+v0P/+0fW8rpO0JEdTG2aba3AdulyWhdO
  ntaN9kRLyZuT8GPdgxg+00lbbwfbIf2RyFHhOTYSIitX4DV4mewcukJddHDUliT3
  lOS9Y1QFOMVvvdeekUafjl1YCNG4OQ2HRPEwA9UchpcARXEU3fbpGmlGZZJCzIxH
  sVymzAw76OAvWkieX3UVcbTUc2Dz3rQXpXkI1E+DmErtwTHGtFukG3xO/Mhbo1r/
  cqqaBdWvm4K6+VRmC02M9yjOVaSrITOmpoKCbORX7+xe81YfRqa/x1GxxW1+6JA0
  0NLLX+ZF30b4Sl/CvwbQkB02cO6GN7VL2cW5AwIDAQABAoIBAFr3isJ0PaWDJ9Qy
  jb9JNjAFCh2lnL0QlL6Uggcb6pAYDcS6bZ4TQn8Zu9hPU++vtnDE1X6AR4qQckaz
  ikWZe2ZjySmQgeH/nHu4H3ZJnqfD1YMrtq77rftKfDG86fvWNakGZG5RZmbuGYQm
  4pdYYxGsgSqYBUm3uEUrJ78dyXWl92kowG2GftZMSrnuP1Z/S2Z511AeENhQmtpM
  aPEZqJ9mga1getX8ZLT3kwbRnmvOOxoHq1nS06U9EcP/IeHHKIa+BqsepEvGS0Kr
  9m9/xmwcCDHYJSz9NTlnK3E5VaRHYpORI6QBbh1zrsb0vMJANnPg/BQKweCaSrrt
  NjGvzFECgYEA5ELvvTNMb+/N+JXznJkzMvR0nErsZ9GpuETJpurmqih07R8/fYy7
  v2tLLWZToZ7iBKNRuJt1TCfQ+GCq1ex8Zjl+WFJRaWwldVPXa5YFrJ5DC1LNAozz
  l/OxuNOQBgdj+ZgaEK0wZeSX3n8Wiswnu/3HQ+PivcU+swq+N/jmv7kCgYEAref+
  sLXh14uHHszr8FyCXDs+z8raV7ivRKMyLXe8eTSBeDy+fbZCugR/67BCtd3s5it6
  WV/rcdzeTzQSgq2G3P1Rsk8jNkJ/VGzIngpJgwkwTxJSzfQRo7fzbh3aaHy684NZ
  B1ww+yjExU9R2USTheYNuV8H2OJCRtpESfx2xJsCgYB0XzvidbjOiK+1wJ1GhUR5
  AfBBjmEgPOAONeOo2bFnpuCV04yG8az2VjkpmDWi/GG2g50yRO90OAht2Lq//aUe
  aMllNfKTkLM4Mdpt2zphWv5LU5d5aWr3WSKOXC3dJP9vTIBdaC54hCZ5JMnVUWgg
  i61/izsaDOl+VkfMOXVK4QKBgAPClV4qwJRRfv1qftt2lJb77PK/NxNYeempAae8
  BAY23WnFHnVHYI/3EvD8oaSfBMVBQWb3TPbsSJ47yP6sU9MpYv/Q+DjvHSOtKnVI
  UaiUpUfAZKvxUARTMN87pAJIWB51w5IGK0Ty77Y4bdOdyPbHL5rHdDr7QWWYyIs0
  +zhrAoGAcC/zmWdOf7vH/aoawj1tS/SHXzgc0sZdhUfhkaZrUMJbM3JB7jUEVaii
  pNXyM4RTpfN16Xqvwb1sRv+xdCv3CceybFIDGpa47P05sdAHzdIHwMGPsO/fCh2W
  0YAz4Oyi5H+gXdpuS7V0Rb+SrvOhBKkGZfzNwAIb98zU2AUh7dY=
type: kubernetes.io/tls



