apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  ports:
  - port: 80 # Порт сетевого балансировщика, на котором будут обслуживаться пользовательские запросы.
    name: plaintext 
    targetPort: 8080 # Порт контейнера, на котором доступно приложение.
  selector: # Метки селектора, использованные в шаблоне подов при создании объекта Deployment.
    app: hello
  type: LoadBalancer

